# Generated by Django 2.2.12 on 2021-03-08 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rekomendasi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='smart_recomm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smart_name', models.CharField(max_length=256)),
                ('cos_sim', models.FloatField()),
            ],
        ),
    ]
