# Generated by Django 2.2.12 on 2021-03-08 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rekomendasi', '0002_smart_recomm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommended_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec1', models.IntegerField()),
                ('rec2', models.IntegerField()),
                ('rec3', models.IntegerField()),
                ('rec4', models.IntegerField()),
                ('rec5', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='smart_recomm',
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='recommended_list',
            name='idx',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rekomendasi.Smartphone'),
        ),
    ]
