# Generated by Django 2.2.12 on 2021-03-11 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rekomendasi', '0003_auto_20210309_0208'),
    ]

    operations = [
        migrations.CreateModel(
            name='smartphone_recomm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smartphone_name', models.CharField(max_length=256)),
                ('cos_sim', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Recommended_list',
        ),
        migrations.DeleteModel(
            name='Smartphone',
        ),
    ]
