# Generated by Django 2.2.12 on 2021-03-13 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rekomendasi', '0006_smartphone_recomm'),
    ]

    operations = [
        migrations.DeleteModel(
            name='smartphone_recomm',
        ),
    ]
