# Generated by Django 2.2.12 on 2021-03-13 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rekomendasi', '0007_delete_smartphone_recomm'),
    ]

    operations = [
        migrations.CreateModel(
            name='smartphone_recomm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smartphone_name', models.CharField(max_length=256)),
                ('ram', models.CharField(max_length=255)),
                ('os', models.CharField(max_length=255)),
                ('cpu', models.CharField(max_length=255)),
                ('battery', models.CharField(max_length=255)),
                ('cos_sim', models.FloatField()),
            ],
        ),
    ]
