# Generated by Django 2.2.12 on 2021-03-14 16:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rekomendasi', '0009_delete_smartphone_recomm'),
    ]

    operations = [
        migrations.CreateModel(
            name='smartphone_recomm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smartphone_name', models.CharField(max_length=256)),
                ('ram', models.CharField(max_length=255)),
                ('os', models.CharField(max_length=255)),
                ('cpu', models.CharField(max_length=255)),
                ('battery', models.CharField(max_length=255)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('cos_sim', models.FloatField()),
            ],
        ),
    ]
