# Generated by Django 2.2.12 on 2021-03-21 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rekomendasi', '0010_smartphone_recomm'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartphone_recomm',
            name='Smartphone_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rekomendasi.Smartphone'),
        ),
    ]
