# Generated by Django 2.2.12 on 2021-03-21 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rekomendasi', '0012_auto_20210322_0215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smartphone_recomm',
            name='battery',
        ),
        migrations.RemoveField(
            model_name='smartphone_recomm',
            name='cpu',
        ),
        migrations.RemoveField(
            model_name='smartphone_recomm',
            name='os',
        ),
        migrations.RemoveField(
            model_name='smartphone_recomm',
            name='ram',
        ),
        migrations.RemoveField(
            model_name='smartphone_recomm',
            name='smartphone_name',
        ),
    ]
