# Generated by Django 2.2.12 on 2021-03-21 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rekomendasi', '0013_auto_20210322_0337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smartphone_recomm',
            name='date',
        ),
    ]
